// Exemplo 01
Bimestre Switch = 
SWITCH(TRUE(),
    dCalendario[Mês] <=2,"Bimestre 1",
    dCalendario[Mês] <=4,"Bimestre 2",
    dCalendario[Mês] <=6,"Bimestre 3",
    dCalendario[Mês] <=8,"Bimestre 4",
    dCalendario[Mês] <=10,"Bimestre 5",
    "Bimestre 6"
)

// Exemplo 02
Faixa Estaria =
SWITCH(TRUE(),
    dClientes[Idade] <= 19, "Jovem",
    dClientes[Idade] <= 59, "Adulto",
    "Sênior"
)

// Exemplo 03
Desconto = 
SWITCH(dClientes[Nivel Escolar],
    "Pós Graduação", 0.2,
    "Superior Completo", 0.1,
    "Superior Incompleto", 0.05,
    0
)

// Exemplo 04
Desconto = 
SWITCH(TRUE(),
    dClientes[Nivel Escolar] = "Pós Graduação", 0.2,
    dClientes[Nivel Escolar] = "Superior Completo", 0.1,
    dClientes[Nivel Escolar] = "Superior Incompleto", 0.05,
    0
)

